project:
  type: website
  preview:
    port: 3100
  render:
    #  List index.qmd first so that / redirects to it
    - /index.qmd
    - /*.qmd
    - individual_assignment
    - tutorials
    - project
    - install_instructions

website:
  title: "DSCI 310"

  page-navigation: true

  repo-url: https://github.com/UBC-DSCI/dsci-310-student
  repo-actions: [edit, source, issue]

  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - href: assessments.qmd
        text: Assessments
      - href: tutorials.qmd
        text: Tutorials
      - href: computer-setup.qmd
        text: Computer Setup

    right:
      - href: coc.qmd
        text: Code of Conduct

  sidebar:
    - title: Assessments
      contents:
        - assessments.qmd

        - text: "---"

        - section: "Individual Assignments"
          contents:
            - individual_assignment/ia1.qmd
            - individual_assignment/ia2.qmd
            - individual_assignment/ia3.qmd
            - individual_assignment/ia4.qmd

        - text: "---"

        - section: "Milestone"
          contents:
            - project/m1.qmd
            - project/m2.qmd

        - text: "---"

        - section: "Teamwork"
          contents:
            - project/teamwork_contract.qmd

    - title: Tutorials
      contents:
        - tutorials.qmd
        - text: "---"
        - tutorials/t1.qmd
        - tutorials/t2.qmd
        - tutorials/t3.qmd
        - tutorials/t4.qmd
        - tutorials/t5.qmd
        - tutorials/t6.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute:
  echo: false
  warning: false

editor:
  markdown:
    wrap: 72
  render-on-save: true
