project:
  type: website

website:
  title: "DSCI 310"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - href: assessments.qmd
        text: Assessments
      - href: computer-setup.qmd
        text: Computer Setup

    right:
      - href: coc.qmd
        text: Code of Conduct

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute:
  echo: false
  warning: false

editor:
  markdown:
    wrap: 72
  render-on-save: true
